@extends('layouts.app')

@section('content')
    <style>
        body:has(.map-screen) { overflow: hidden; }
        .map-screen { height: calc(100dvh - 86px); min-height: 650px; display: grid; grid-template-rows: clamp(132px,15vh,146px) 64px minmax(440px,1fr); gap: 10px; }
        .map-hero { position: relative; overflow: hidden; display: flex; align-items: center; padding: 22px 28px; border-radius: 8px; color: white; background: linear-gradient(90deg,rgba(4,25,55,.82),rgba(4,25,55,.28),rgba(4,25,55,.05)),url('{{ asset('images/dashboard-hero-guatemala.png') }}') center 58%/cover; box-shadow: var(--shadow); }
        .map-hero .eyebrow { margin-bottom: 7px; font-size: .72rem; opacity: .95; }.map-hero h1 { font-size: clamp(2rem,2.4vw,2.5rem); line-height: 1; }.map-hero .subtitle { margin-top: 7px; font-size: .9rem; }.map-hero .hero-note { position: absolute; top: 17px; right: 22px; display: flex; gap: 7px; max-width: 190px; font-size: .68rem; font-weight: 800; }.map-hero .hero-note svg { width: 18px; }
        .map-toolbar { display: grid; grid-template-columns: minmax(360px,.8fr) minmax(0,1.2fr); gap: 18px; align-items: end; }.map-toolbar label { display: block; font-size: .68rem; }.map-select-box { position: relative; display: block; margin-top: 3px; }.map-select-box svg { position: absolute; z-index: 1; left: 11px; top: 50%; width: 17px; transform: translateY(-50%); color: var(--muted); pointer-events: none; }.map-select-box select { height: 39px; min-height: 39px; padding: 5px 10px 5px 37px; font-size: .72rem; }
        .map-help { height: 54px; display: grid; grid-template-columns: 28px 1fr; gap: 10px; align-items: center; padding: 8px 13px; border-radius: 8px; color: var(--muted); background: #eaf5ff; font-size: .66rem; }.map-help > svg { width: 20px; color: var(--blue); }.map-help strong { display: block; margin-bottom: 2px; color: var(--ink); }
        .map-content { min-height: 0; display: grid; grid-template-columns: minmax(0,1.28fr) minmax(400px,.82fr); gap: 10px; }.map-card { min-height: 0; position: relative; overflow: hidden; padding: 0; }.map-card #national-map { width: 100%; height: 100%; min-height: 0; border: 0; border-radius: 8px; }.map-legend { position: absolute; z-index: 500; top: 12px; right: 12px; display: grid; gap: 7px; padding: 9px 11px; border-radius: 7px; background: rgba(255,255,255,.94); box-shadow: 0 8px 18px rgba(7,22,74,.12); font-size: .63rem; color: var(--muted); }.legend-dot { display: inline-block; width: 9px; height: 9px; margin-right: 6px; border-radius: 50%; background: var(--green); }.legend-dot.maintenance { background: var(--amber); }.legend-dot.inactive { background: var(--red); }
        .map-side { min-height: 0; display: grid; grid-template-rows: 215px minmax(0,1fr); gap: 10px; }.department-summary,.visible-farms { min-height: 0; overflow: hidden; padding: 12px 14px; }.map-card-title { display: flex; align-items: center; justify-content: space-between; gap: 8px; margin-bottom: 10px; }.map-card-title h2 { display: flex; align-items: center; gap: 8px; font-size: .9rem; }.map-card-title h2 svg { width: 18px; color: var(--green); }.map-card-title span { color: var(--blue); font-size: .62rem; }
        .department-head { display: flex; gap: 10px; align-items: center; }.department-icon { width: 45px; height: 45px; display: grid; place-items: center; border-radius: 7px; color: var(--green-dark); background: var(--mint); }.department-icon svg { width: 24px; }.department-head h3 { font-size: .8rem; }.department-head p { margin-top: 3px; color: var(--muted); font-size: .62rem; }
        .department-kpis { display: grid; grid-template-columns: repeat(4,minmax(0,1fr)); gap: 7px; margin-top: 12px; }.department-kpi { min-width: 0; padding: 8px; border: 1px solid var(--line); border-radius: 7px; }.department-kpi svg { width: 18px; color: var(--blue); }.department-kpi span { display: block; margin-top: 4px; color: var(--muted); font-size: .56rem; }.department-kpi strong { display: block; margin-top: 4px; font-size: .82rem; white-space: nowrap; }
        .visible-farms { display: grid; grid-template-rows: 30px minmax(0,1fr) 34px; }.visible-farms .map-card-title { margin: 0; }.visible-table-wrap { min-height: 0; overflow: hidden; border: 1px solid var(--line); border-radius: 6px; }.visible-table { table-layout: fixed; font-size: .61rem; }.visible-table th,.visible-table td { height: 31px; padding: 4px 7px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }.visible-table th { background: #f5f9fd; }.farm-map-name { display: flex; align-items: center; gap: 7px; }.farm-map-thumb { width: 30px; height: 20px; flex: 0 0 auto; border-radius: 3px; object-fit: cover; }.farm-map-status { display: inline-flex; align-items: center; gap: 5px; }.farm-map-status::before { content: ''; width: 8px; height: 8px; border-radius: 50%; background: var(--green); }.farm-map-status.maintenance::before { background: var(--amber); }.farm-map-status.inactive::before { background: var(--red); }.map-tip { display: flex; align-items: center; gap: 7px; margin-top: 7px; padding: 6px 9px; border-radius: 6px; background: var(--mint); color: var(--green-dark); font-size: .59rem; }.map-tip svg { width: 16px; }
        @media(max-width:1180px){body:has(.map-screen){overflow:auto}.map-screen{height:auto;grid-template-rows:auto}.map-toolbar,.map-content{grid-template-columns:1fr}.map-card{height:560px}.map-side{grid-template-rows:auto}.department-summary{min-height:230px}.visible-farms{min-height:400px}}
        @media(max-width:700px){.department-kpis{grid-template-columns:repeat(2,1fr)}.map-hero .hero-note{display:none}}
    </style>

    <div class="map-screen">
        <section class="map-hero"><div><p class="eyebrow">RMGS - Registro y Monitoreo de Generacion Solar Guatemala</p><h1>Ver mapa</h1><p class="subtitle">Explora la distribucion de las granjas solares en Guatemala.</p></div><div class="hero-note"><i data-lucide="map-pin"></i><span>Guatemala, un pais con mas energia limpia</span></div></section>
        <section class="map-toolbar"><label>Selecciona un departamento<span class="map-select-box"><i data-lucide="map-pin"></i><select id="map-department-filter"><option value="">Todos los departamentos</option>@foreach($departments as $department)<option value="{{ $department->name }}">{{ $department->name }}</option>@endforeach</select></span></label><div class="map-help"><i data-lucide="info"></i><p><strong>Selecciona un departamento para explorar sus granjas solares.</strong>Puedes hacer clic en los marcadores para ver mas informacion.</p></div></section>
        <section class="map-content">
            <article class="card map-card"><div id="national-map"></div><div class="map-legend"><span><i class="legend-dot"></i>Granja operativa</span><span><i class="legend-dot maintenance"></i>En mantenimiento</span><span><i class="legend-dot inactive"></i>Inactiva</span></div></article>
            <aside class="map-side">
                <section class="card department-summary"><div class="map-card-title"><h2><i data-lucide="map-pin"></i>Resumen del departamento</h2><span>Cambiar departamento</span></div><div class="department-head"><span class="department-icon"><i data-lucide="landmark"></i></span><div><h3 id="department-name">Todos los departamentos</h3><p id="department-caption">Vista general de Guatemala</p></div></div><div class="department-kpis"><div class="department-kpi"><i data-lucide="landmark"></i><span>Granjas solares</span><strong id="map-stat-farms">{{ $stats['farms'] }}</strong></div><div class="department-kpi"><i data-lucide="grid-2x2"></i><span>Paneles instalados</span><strong id="map-stat-panels">{{ number_format($stats['panels']) }}</strong></div><div class="department-kpi"><i data-lucide="zap"></i><span>Capacidad instalada</span><strong id="map-stat-capacity">{{ number_format($stats['capacity_kw'],1) }} kW</strong></div><div class="department-kpi"><i data-lucide="leaf"></i><span>CO2 evitado</span><strong id="map-stat-co2">{{ number_format($stats['co2_tons'],1) }} t</strong></div></div></section>
                <section class="card visible-farms"><div class="map-card-title"><h2><i data-lucide="list"></i>Granjas visibles en el mapa</h2><span><strong id="visible-map-count">{{ $farms->count() }}</strong> mostradas</span></div><div class="visible-table-wrap"><table class="visible-table"><thead><tr><th style="width:34%">Nombre</th><th style="width:25%">Departamento</th><th style="width:22%">Capacidad (kW)</th><th style="width:19%">Estado</th></tr></thead><tbody id="map-farms-body">@foreach($farms as $farm)<tr data-map-farm-id="{{ $farm->id }}" data-department="{{ $farm->department->name }}"><td><span class="farm-map-name"><img class="farm-map-thumb" src="{{ asset('images/dashboard-hero-guatemala.png') }}" alt=""><strong>{{ $farm->name }}</strong></span></td><td>{{ $farm->department->name }}</td><td>{{ number_format($farm->installedCapacityKw(),1) }}</td><td><span class="farm-map-status {{ $farm->status }}">{{ $farm->status==='active'?'Activa':($farm->status==='maintenance'?'Mantenimiento':'Inactiva') }}</span></td></tr>@endforeach</tbody></table></div><div class="map-tip"><i data-lucide="leaf"></i>Haz clic en una granja o marcador para ver sus detalles.</div></section>
            </aside>
        </section>
    </div>
    <script>
        const mapFarms=@json($mapFarms),departmentFilter=document.getElementById('map-department-filter'),farmRows=[...document.querySelectorAll('[data-map-farm-id]')],nationalMap=L.map('national-map').setView([15.2,-90.35],7),markers=new Map();
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap'}).addTo(nationalMap);
        mapFarms.forEach(farm=>{const color=farm.status==='maintenance'?'#f2a900':(farm.status==='inactive'?'#ef4444':'#0aa574'),marker=L.circleMarker([farm.lat,farm.lng],{radius:8,color:'#fff',weight:3,fillColor:color,fillOpacity:1}).addTo(nationalMap).bindPopup(`<strong>${farm.name}</strong><br>${farm.municipality}, ${farm.department}<br>${Number(farm.capacity_kw).toFixed(1)} kW<br>${Number(farm.panels).toLocaleString()} paneles`);markers.set(Number(farm.id),marker)});
        function updateMap(){const selected=departmentFilter.value,visible=mapFarms.filter(farm=>!selected||farm.department===selected);mapFarms.forEach(farm=>{const marker=markers.get(Number(farm.id));if(!selected||farm.department===selected)marker.addTo(nationalMap);else marker.remove()});farmRows.forEach(row=>row.hidden=!!selected&&row.dataset.department!==selected);document.getElementById('visible-map-count').textContent=visible.length;document.getElementById('department-name').textContent=selected||'Todos los departamentos';document.getElementById('department-caption').textContent=selected?'Resumen departamental':'Vista general de Guatemala';document.getElementById('map-stat-farms').textContent=visible.length;document.getElementById('map-stat-panels').textContent=visible.reduce((sum,farm)=>sum+Number(farm.panels),0).toLocaleString();document.getElementById('map-stat-capacity').textContent=`${visible.reduce((sum,farm)=>sum+Number(farm.capacity_kw),0).toLocaleString(undefined,{maximumFractionDigits:1})} kW`;document.getElementById('map-stat-co2').textContent=`${visible.reduce((sum,farm)=>sum+Number(farm.co2_tons),0).toLocaleString(undefined,{maximumFractionDigits:1})} t`;if(visible.length){const bounds=L.latLngBounds(visible.map(farm=>[farm.lat,farm.lng]));nationalMap.fitBounds(bounds.pad(.35),{maxZoom:9})}else nationalMap.setView([15.2,-90.35],7)}
        departmentFilter.addEventListener('input',updateMap);farmRows.forEach(row=>row.addEventListener('click',()=>{const marker=markers.get(Number(row.dataset.mapFarmId));nationalMap.setView(marker.getLatLng(),11);marker.openPopup()}));window.setTimeout(()=>nationalMap.invalidateSize(),100);
    </script>
@endsection
