@extends('layouts.app')

@section('content')
    <style>
        body:has(.alerts-screen) { overflow: hidden; }
        .alerts-screen { height: calc(100dvh - 86px); min-height: 650px; display: grid; grid-template-rows: clamp(132px,15vh,146px) 108px minmax(410px,1fr); gap: 10px; }
        .alerts-hero { position: relative; overflow: hidden; display: flex; align-items: center; padding: 22px 28px; border-radius: 8px; color: white; background: linear-gradient(90deg,rgba(4,25,55,.82),rgba(4,25,55,.28),rgba(4,25,55,.05)),url('{{ asset('images/dashboard-hero-guatemala.png') }}') center 58%/cover; box-shadow: var(--shadow); }
        .alerts-hero .eyebrow { margin-bottom: 7px; font-size: .72rem; opacity: .95; }.alerts-hero h1 { font-size: clamp(2rem,2.4vw,2.5rem); line-height: 1; }.alerts-hero .subtitle { max-width: 390px; margin-top: 7px; font-size: .9rem; line-height: 1.25; }
        .alerts-hero .hero-note { position: absolute; top: 17px; right: 22px; display: flex; gap: 7px; max-width: 190px; font-size: .68rem; font-weight: 800; }.alerts-hero .hero-note svg { width: 18px; }
        .alert-kpis { grid-template-columns: repeat(4,minmax(0,1fr)); }.alert-kpi { min-width: 0; display: grid; grid-template-columns: 56px minmax(0,1fr); gap: 13px; align-items: center; padding: 12px 16px; }
        .alert-kpi-icon { width: 54px; height: 54px; display: grid; place-items: center; border-radius: 8px; }.alert-kpi-icon svg { width: 28px; }.alert-kpi-icon.high { color: var(--red); background: #fee8e8; }.alert-kpi-icon.medium { color: #e69a00; background: #fff3d6; }.alert-kpi-icon.low { color: var(--blue); background: var(--blue-soft); }.alert-kpi-icon.resolved { color: var(--green-dark); background: var(--mint); }
        .alert-kpi-label { margin-bottom: 5px; font-size: .72rem; }.alert-kpi-value { font-size: 1.75rem; line-height: 1; font-weight: 900; }.alert-kpi-trend { margin-top: 6px; font-size: .72rem; font-weight: 900; }.alert-kpi-trend.bad { color: var(--red); }.alert-kpi-trend.good { color: var(--green); }.alert-kpi-trend span { margin-left: 6px; color: var(--muted); font-size: .61rem; font-weight: 700; }
        .alerts-content { min-height: 0; display: grid; grid-template-columns: minmax(0,1.65fr) minmax(330px,.65fr); gap: 10px; }.alerts-main { min-height: 0; display: grid; grid-template-rows: 76px minmax(0,1fr); gap: 10px; }.alerts-side { min-height: 0; display: grid; grid-template-rows: 1.1fr .9fr; gap: 10px; }
        .alert-filters { display: grid; grid-template-columns: 1.25fr 1fr .8fr .8fr; gap: 10px; padding: 8px 14px; }.alert-filters label { display: block; font-size: .64rem; }.alert-filter-box { position: relative; display: block; margin-top: 3px; }.alert-filter-box svg { position: absolute; z-index: 1; left: 10px; top: 50%; width: 16px; transform: translateY(-50%); color: var(--muted); pointer-events: none; }.alert-filters input,.alert-filters select { height: 35px; min-height: 35px; padding: 4px 8px 4px 32px; font-size: .68rem; }
        .alerts-list-card { min-height: 0; overflow: hidden; padding: 11px 14px; }.alerts-list-card h2 { margin-bottom: 8px; font-size: .95rem; }.alerts-table-wrap { min-height: 0; overflow: hidden; border: 1px solid var(--line); border-radius: 7px; }.alerts-table { table-layout: fixed; font-size: .65rem; }.alerts-table th,.alerts-table td { height: 43px; padding: 5px 8px; white-space: normal; line-height: 1.2; }.alerts-table th { height: 30px; background: #f5f9fd; }.alert-type { display: flex; align-items: center; gap: 7px; font-weight: 700; }.alert-type svg { width: 17px; color: var(--red); }.priority,.alert-state { display: inline-flex; min-width: 58px; justify-content: center; padding: 5px 8px; border-radius: 6px; font-size: .61rem; font-weight: 800; }.priority.high { color: var(--red); background: #fee8e8; }.priority.medium { color: #b97800; background: #fff3d6; }.priority.low { color: var(--blue); background: var(--blue-soft); }.alert-state.active { color: var(--red); background: #fee8e8; }.alert-state.resolved { color: var(--green-dark); background: var(--mint); }.alert-action { border: 0; background: transparent; color: #46618f; cursor: pointer; }.alert-action svg { width: 17px; }
        .side-card { min-height: 0; overflow: hidden; padding: 11px 14px; }.side-card .card-title { margin-bottom: 5px; }.side-card .card-title h2 { display: flex; align-items: center; gap: 8px; font-size: .9rem; }.side-card .card-title svg { width: 18px; color: #58709b; }
        .recent-list,.recommendation-list { display: grid; gap: 0; }.recent-alert { display: grid; grid-template-columns: 23px 1fr auto; gap: 7px; align-items: center; min-height: 46px; border-bottom: 1px solid #e8eff7; font-size: .63rem; }.recent-alert svg { width: 16px; color: var(--red); }.recent-alert p { margin-top: 2px; color: var(--muted); }.recent-alert time { color: var(--muted); white-space: nowrap; }
        .recommendation { display: grid; grid-template-columns: 24px 1fr 16px; gap: 8px; align-items: center; min-height: 48px; padding: 5px 7px; border-bottom: 1px solid #e8eff7; font-size: .63rem; color: var(--muted); }.recommendation > svg:first-child { width: 17px; color: var(--green); }.recommendation > svg:last-child { width: 14px; }
        .empty-alerts { padding: 35px; text-align: center; color: var(--muted); }
        @media(max-width:1180px){body:has(.alerts-screen){overflow:auto}.alerts-screen{height:auto;grid-template-rows:auto}.alert-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.alerts-content{grid-template-columns:1fr}.alerts-main{min-height:520px}.alerts-side{grid-template-columns:1fr 1fr;grid-template-rows:auto}.side-card{min-height:280px}}
        @media(max-width:700px){.alert-kpis,.alert-filters,.alerts-side{grid-template-columns:1fr}.alerts-hero .hero-note{display:none}}
    </style>

    <div class="alerts-screen">
        <section class="alerts-hero"><div><p class="eyebrow">Control operativo</p><h1>Alertas de desempeno</h1><p class="subtitle">Prioriza granjas con produccion baja y marca el seguimiento realizado.</p></div><div class="hero-note"><i data-lucide="triangle-alert"></i><span>Una alerta nace al caer 20% o mas</span></div></section>
        <section class="grid alert-kpis">
            <article class="card alert-kpi"><span class="alert-kpi-icon high"><i data-lucide="triangle-alert"></i></span><div><p class="alert-kpi-label">Alta prioridad</p><p class="alert-kpi-value">{{ $stats['high'] }}</p><p class="alert-kpi-trend bad">Desviacion +25%</p></div></article>
            <article class="card alert-kpi"><span class="alert-kpi-icon medium"><i data-lucide="triangle-alert"></i></span><div><p class="alert-kpi-label">Media prioridad</p><p class="alert-kpi-value">{{ $stats['medium'] }}</p><p class="alert-kpi-trend good">Desviacion 20% a 24%</p></div></article>
            <article class="card alert-kpi"><span class="alert-kpi-icon low"><i data-lucide="info"></i></span><div><p class="alert-kpi-label">Baja prioridad</p><p class="alert-kpi-value">{{ $stats['low'] }}</p><p class="alert-kpi-trend good">En observacion</p></div></article>
            <article class="card alert-kpi"><span class="alert-kpi-icon resolved"><i data-lucide="circle-check"></i></span><div><p class="alert-kpi-label">Alertas resueltas</p><p class="alert-kpi-value">{{ $stats['resolved'] }}</p><p class="alert-kpi-trend good">Historial completo</p></div></article>
        </section>
        <section class="alerts-content">
            <div class="alerts-main">
                <section class="card alert-filters"><label>Buscar alerta<span class="alert-filter-box"><i data-lucide="search"></i><input id="alert-search" type="search" placeholder="Buscar por granja..."></span></label><label>Departamento<span class="alert-filter-box"><i data-lucide="map-pin"></i><select id="alert-department"><option value="">Todos los departamentos</option>@foreach($departments as $department)<option value="{{ $department->name }}">{{ $department->name }}</option>@endforeach</select></span></label><label>Prioridad<span class="alert-filter-box"><i data-lucide="triangle-alert"></i><select id="alert-priority"><option value="">Todas</option><option value="high">Alta</option><option value="medium">Media</option><option value="low">Baja</option></select></span></label><label>Estado<span class="alert-filter-box"><i data-lucide="circle"></i><select id="alert-status"><option value="">Todos</option><option value="active">Activa</option><option value="resolved">Resuelta</option></select></span></label></section>
                <section class="card alerts-list-card"><h2>Listado de alertas</h2><div class="alerts-table-wrap">@if($alerts->isEmpty())<div class="empty-alerts">No hay alertas registradas.</div>@else<table class="alerts-table"><thead><tr><th style="width:13%">Periodo</th><th style="width:19%">Granja solar</th><th style="width:17%">Tipo</th><th style="width:23%">Descripcion</th><th style="width:10%">Prioridad</th><th style="width:10%">Estado</th><th style="width:8%">Acciones</th></tr></thead><tbody>@foreach($alerts as $alert)@php $priority=$alert->deviation_percent>=25?'high':($alert->deviation_percent>=20?'medium':'low'); @endphp<tr class="alert-row-filter" data-search="{{ strtolower($alert->solarFarm->name) }}" data-department="{{ $alert->solarFarm->department->name }}" data-priority="{{ $priority }}" data-status="{{ $alert->status }}"><td>{{ $alert->period->format('m/Y') }}</td><td><strong>{{ $alert->solarFarm->name }}</strong></td><td><span class="alert-type"><i data-lucide="trending-down"></i>Produccion baja</span></td><td>Generacion {{ number_format($alert->deviation_percent,1) }}% por debajo de lo esperado.</td><td><span class="priority {{ $priority }}">{{ $priority==='high'?'Alta':($priority==='medium'?'Media':'Baja') }}</span></td><td><span class="alert-state {{ $alert->status }}">{{ $alert->status==='active'?'Activa':'Resuelta' }}</span></td><td><form method="post" action="{{ route('alerts.update',$alert) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $alert->status==='active'?'resolved':'active' }}"><button class="alert-action" type="submit" title="{{ $alert->status==='active'?'Marcar resuelta':'Reactivar' }}"><i data-lucide="{{ $alert->status==='active'?'circle-check':'rotate-ccw' }}"></i></button></form></td></tr>@endforeach</tbody></table>@endif</div></section>
            </div>
            <aside class="alerts-side">
                <section class="card side-card"><div class="card-title"><h2><i data-lucide="bell"></i>Alertas recientes</h2></div><div class="recent-list">@forelse($alerts->take(5) as $alert)<div class="recent-alert"><i data-lucide="trending-down"></i><div><strong>Produccion baja</strong><p>{{ $alert->solarFarm->name }}</p></div><time>{{ $alert->period->format('m/Y') }}</time></div>@empty<div class="empty-alerts">Sin alertas recientes.</div>@endforelse</div></section>
                <section class="card side-card" id="recommendations"><div class="card-title"><h2><i data-lucide="lightbulb"></i>Recomendaciones</h2></div><div class="recommendation-list"><div class="recommendation"><i data-lucide="leaf"></i><span>Revisa periodicamente la limpieza de los paneles solares.</span><i data-lucide="chevron-right"></i></div><div class="recommendation"><i data-lucide="bar-chart-3"></i><span>Configura umbrales segun el rendimiento de cada granja.</span><i data-lucide="chevron-right"></i></div><div class="recommendation"><i data-lucide="settings"></i><span>Programa mantenimientos preventivos para mayor disponibilidad.</span><i data-lucide="chevron-right"></i></div></div></section>
            </aside>
        </section>
    </div>
    <script>
        const alertRows=[...document.querySelectorAll('.alert-row-filter')],alertSearch=document.getElementById('alert-search'),alertDepartment=document.getElementById('alert-department'),alertPriority=document.getElementById('alert-priority'),alertStatus=document.getElementById('alert-status');function filterAlerts(){const query=alertSearch.value.trim().toLowerCase();alertRows.forEach(row=>row.hidden=!!((query&&!row.dataset.search.includes(query))||(alertDepartment.value&&row.dataset.department!==alertDepartment.value)||(alertPriority.value&&row.dataset.priority!==alertPriority.value)||(alertStatus.value&&row.dataset.status!==alertStatus.value)))}[alertSearch,alertDepartment,alertPriority,alertStatus].forEach(control=>control.addEventListener('input',filterAlerts));
    </script>
@endsection
