@extends('layouts.app')

@section('content')
    <style>
        body:has(.projections-screen) { overflow: hidden; }
        .projections-screen { height: calc(100dvh - 86px); min-height: 650px; display: grid; grid-template-rows: clamp(132px,15vh,146px) 108px minmax(245px,1fr) 176px; gap: 10px; }
        .projections-hero { position: relative; overflow: hidden; display: flex; align-items: center; padding: 22px 28px; border-radius: 8px; color: white; background: linear-gradient(90deg,rgba(4,25,55,.82),rgba(4,25,55,.28),rgba(4,25,55,.05)),url('{{ asset('images/dashboard-hero-guatemala.png') }}') center 58%/cover; box-shadow: var(--shadow); }
        .projections-hero .eyebrow { margin-bottom: 7px; font-size: .72rem; opacity: .95; }.projections-hero h1 { font-size: clamp(2rem,2.4vw,2.5rem); line-height: 1; }.projections-hero .subtitle { margin-top: 7px; font-size: .9rem; }.projections-hero .caption { margin-top: 5px; font-size: .7rem; opacity: .92; }
        .projections-hero .hero-note { position: absolute; top: 17px; right: 22px; display: flex; gap: 7px; max-width: 190px; font-size: .68rem; font-weight: 800; }.projections-hero .hero-note svg { width: 18px; }
        .projection-kpis { grid-template-columns: repeat(4,minmax(0,1fr)); }.projection-kpi { min-width: 0; display: grid; grid-template-columns: 56px minmax(0,1fr); gap: 13px; align-items: center; padding: 12px 16px; }.projection-kpi-icon { width: 54px; height: 54px; display: grid; place-items: center; border-radius: 8px; color: var(--blue); background: var(--blue-soft); }.projection-kpi-icon.green { color: var(--green-dark); background: var(--mint); }.projection-kpi-icon svg { width: 28px; }
        .projection-kpi-label { margin-bottom: 5px; font-size: .7rem; line-height: 1.15; }.projection-kpi-value { font-size: clamp(1.2rem,1.5vw,1.65rem); line-height: 1; font-weight: 900; white-space: nowrap; }.projection-kpi-trend { margin-top: 6px; color: var(--green); font-size: .72rem; font-weight: 900; }.projection-kpi-trend span { margin-left: 6px; color: var(--muted); font-size: .61rem; font-weight: 700; }
        .projection-content { min-height: 0; display: grid; grid-template-columns: minmax(0,1.5fr) minmax(340px,.7fr); gap: 10px; }.projection-chart-card { min-height: 0; display: grid; grid-template-rows: 34px minmax(0,1fr); padding: 12px 16px; overflow: hidden; }.projection-chart-card .card-title { margin: 0; }.projection-chart-card h2 { font-size: .95rem; }.projection-chart-wrap { min-height: 0; }.projection-chart-wrap canvas { width: 100%!important; height: 100%!important; }.range-picker { min-height: 32px; padding: 0 10px; font-size: .68rem; }
        .scenario-card { min-height: 0; display: grid; grid-template-rows: 30px repeat(3,1fr); gap: 7px; padding: 11px 12px; overflow: hidden; }.scenario-card h2 { font-size: .9rem; }.scenario { min-height: 0; display: grid; grid-template-columns: 48px minmax(0,1fr) auto; gap: 10px; align-items: center; padding: 7px 9px; border: 1px solid var(--line); border-radius: 7px; }.scenario-icon { width: 44px; height: 44px; display: grid; place-items: center; border-radius: 7px; }.scenario-icon svg { width: 24px; }.scenario.optimistic .scenario-icon { color: var(--green-dark); background: var(--mint); }.scenario.base .scenario-icon { color: var(--blue); background: var(--blue-soft); }.scenario.conservative .scenario-icon { color: var(--red); background: #fee8e8; }.scenario h3 { font-size: .7rem; }.scenario-value { margin-top: 3px; font-size: 1rem; font-weight: 900; white-space: nowrap; }.scenario p { margin-top: 3px; color: var(--muted); font-size: .58rem; }.scenario-growth { align-self: start; font-size: .85rem; font-weight: 900; white-space: nowrap; }.optimistic .scenario-growth,.base .scenario-growth { color: var(--green); }.conservative .scenario-growth { color: var(--red); }
        .projection-table-card { min-height: 0; overflow: hidden; padding: 8px 14px; }.projection-table-card h2 { margin-bottom: 5px; font-size: .9rem; }.projection-table { table-layout: fixed; font-size: .64rem; }.projection-table th,.projection-table td { height: 21px; padding: 2px 8px; text-align: center; white-space: nowrap; }.projection-table th { background: #f5f9fd; }.projection-table td:first-child,.projection-table th:first-child { text-align: left; }
        @media(max-width:1180px){body:has(.projections-screen){overflow:auto}.projections-screen{height:auto;grid-template-rows:auto}.projection-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.projection-content{grid-template-columns:1fr}.projection-chart-card{height:380px}.scenario-card{min-height:430px}.projection-table-card{min-height:280px}}
        @media(max-width:700px){.projection-kpis{grid-template-columns:1fr}.projections-hero .hero-note{display:none}}
    </style>

    <div class="projections-screen">
        <section class="projections-hero"><div><p class="eyebrow">Escenarios {{ $startYear }} - {{ $endYear }}</p><h1>Proyecciones</h1><p class="subtitle">Estimacion de crecimiento con base conservadora, esperada y optimista.</p><p class="caption">La base parte del historial registrado y aplica crecimiento anual simple.</p></div><div class="hero-note"><i data-lucide="line-chart"></i><span>Conservador 3%, base 8%, optimista 12%</span></div></section>
        <section class="grid projection-kpis">
            <article class="card projection-kpi"><span class="projection-kpi-icon green"><i data-lucide="leaf"></i></span><div><p class="projection-kpi-label">Generacion proyectada ({{ $endYear }})</p><p class="projection-kpi-value">{{ number_format($stats['projected_generation']) }} kWh</p><p class="projection-kpi-trend">+36% <span>vs. {{ $startYear }}</span></p></div></article>
            <article class="card projection-kpi"><span class="projection-kpi-icon"><i data-lucide="bar-chart-3"></i></span><div><p class="projection-kpi-label">Capacidad proyectada</p><p class="projection-kpi-value">{{ number_format($stats['projected_capacity'],1) }} kW</p><p class="projection-kpi-trend">+36% <span>vs. {{ $startYear }}</span></p></div></article>
            <article class="card projection-kpi"><span class="projection-kpi-icon"><i data-lucide="users"></i></span><div><p class="projection-kpi-label">Granjas en proyeccion</p><p class="projection-kpi-value">{{ $stats['projected_farms'] }}</p><p class="projection-kpi-trend">+100% <span>vs. {{ $startYear }}</span></p></div></article>
            <article class="card projection-kpi"><span class="projection-kpi-icon green"><i data-lucide="cloud"></i></span><div><p class="projection-kpi-label">CO2 evitado acumulado</p><p class="projection-kpi-value">{{ number_format($stats['accumulated_co2'],1) }} t</p><p class="projection-kpi-trend">Impacto {{ $startYear }}-{{ $endYear }}</p></div></article>
        </section>
        <section class="projection-content">
            <article class="card projection-chart-card"><div class="card-title"><h2>Generacion historica y proyeccion</h2><span class="month-picker range-picker">{{ $startYear }} - {{ $endYear }}<i data-lucide="chevron-down"></i></span></div><div class="projection-chart-wrap"><canvas id="projection-chart"></canvas></div></article>
            <aside class="card scenario-card"><h2>Escenarios de proyeccion {{ $endYear }}</h2>@php $last=$projectionRows->last(); @endphp<div class="scenario optimistic"><span class="scenario-icon"><i data-lucide="trending-up"></i></span><div><h3>Escenario optimista</h3><div class="scenario-value">{{ number_format($last['optimistic']) }} kWh</div><p>Mayor crecimiento y nuevas granjas.</p></div><span class="scenario-growth">+57%</span></div><div class="scenario base"><span class="scenario-icon"><i data-lucide="bar-chart-3"></i></span><div><h3>Escenario base</h3><div class="scenario-value">{{ number_format($last['base']) }} kWh</div><p>Crecimiento segun el desempeño actual.</p></div><span class="scenario-growth">+36%</span></div><div class="scenario conservative"><span class="scenario-icon"><i data-lucide="trending-down"></i></span><div><h3>Escenario conservador</h3><div class="scenario-value">{{ number_format($last['conservative']) }} kWh</div><p>Condiciones adversas y expansion limitada.</p></div><span class="scenario-growth">+13%</span></div></aside>
        </section>
        <section class="card projection-table-card"><h2>Comparativa por año (Generacion proyectada)</h2><table class="projection-table"><thead><tr><th>Año</th><th>Escenario conservador (kWh)</th><th>Escenario base (kWh)</th><th>Escenario optimista (kWh)</th><th>Variacion base vs. año anterior</th></tr></thead><tbody>@foreach($projectionRows as $index=>$row)<tr><td><strong>{{ $row['year'] }}</strong></td><td>{{ number_format($row['conservative']) }}</td><td>{{ number_format($row['base']) }}</td><td>{{ number_format($row['optimistic']) }}</td><td>{{ $index===0?'Base':'+8.0%' }}</td></tr>@endforeach</tbody></table></section>
    </div>
    <script>
        const projectionStyle=getComputedStyle(document.documentElement),projectionGrid=projectionStyle.getPropertyValue('--line').trim(),projectionText=projectionStyle.getPropertyValue('--muted').trim(),projectionRows=@json($projectionRows->values()),projectionLabels=projectionRows.map(row=>row.year);
        new Chart(document.getElementById('projection-chart'),{type:'line',data:{labels:projectionLabels,datasets:[{label:'Escenario base',data:projectionRows.map(row=>row.base),borderColor:'#1689f4',borderDash:[7,5],tension:.25,pointRadius:3,borderWidth:2},{label:'Escenario optimista',data:projectionRows.map(row=>row.optimistic),borderColor:'#0aa574',borderDash:[7,5],tension:.25,pointRadius:0,borderWidth:2},{label:'Escenario conservador',data:projectionRows.map(row=>row.conservative),borderColor:'#ef4444',borderDash:[7,5],tension:.25,pointRadius:0,borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{color:projectionText,usePointStyle:true,font:{size:9}}}},scales:{x:{grid:{color:projectionGrid},ticks:{color:projectionText,font:{size:9}}},y:{grid:{color:projectionGrid},ticks:{color:projectionText,font:{size:9}}}}}});
    </script>
@endsection
