@extends('layouts.app')

@section('content')
    @php
        $seriesValues = collect($generationSeries)->pluck('actual');
        $maxGeneration = $seriesValues->max() ?? 0;
        $minGeneration = $seriesValues->min() ?? 0;
    @endphp
    <style>
        body:has(.reports-screen) { overflow: hidden; }
        .reports-screen { height: calc(100dvh - 86px); min-height: 650px; display: grid; grid-template-rows: clamp(132px,15vh,146px) 108px 62px 112px minmax(230px,1fr); gap: 9px; }
        .reports-hero { position: relative; overflow: hidden; display: flex; align-items: center; padding: 22px 28px; border-radius: 8px; color: white; background: linear-gradient(90deg,rgba(4,25,55,.82),rgba(4,25,55,.28),rgba(4,25,55,.05)),url('{{ asset('images/dashboard-hero-guatemala.png') }}') center 58%/cover; box-shadow: var(--shadow); }
        .reports-hero .eyebrow { margin-bottom: 7px; font-size: .72rem; opacity: .95; }.reports-hero h1 { font-size: clamp(2rem,2.4vw,2.5rem); line-height: 1; }.reports-hero .subtitle { margin-top: 7px; font-size: .9rem; }
        .reports-hero .hero-note { position: absolute; top: 17px; right: 22px; display: flex; gap: 7px; max-width: 190px; font-size: .68rem; font-weight: 800; }.reports-hero .hero-note svg { width: 18px; }
        .report-kpis { grid-template-columns: repeat(4,minmax(0,1fr)); }
        .report-kpi { min-width: 0; display: grid; grid-template-columns: 54px minmax(0,1fr); gap: 13px; align-items: center; padding: 12px 16px; }
        .report-kpi-icon { width: 52px; height: 52px; display: grid; place-items: center; border-radius: 8px; color: var(--green-dark); background: var(--mint); }.report-kpi-icon.blue { color: var(--blue); background: var(--blue-soft); }.report-kpi-icon svg { width: 27px; }
        .report-kpi-label { margin-bottom: 5px; font-size: .72rem; white-space: nowrap; }.report-kpi-value { font-size: clamp(1.25rem,1.55vw,1.7rem); line-height: 1; font-weight: 900; white-space: nowrap; }.report-kpi-trend { margin-top: 6px; color: var(--green); font-size: .72rem; font-weight: 900; }.report-kpi-trend span { margin-left: 6px; color: var(--muted); font-size: .61rem; font-weight: 700; }
        .report-filters { display: grid; grid-template-columns: repeat(4,minmax(0,1fr)); gap: 12px; padding: 7px 14px; }.report-filters label { display: block; font-size: .64rem; }.report-filter-box { position: relative; display: block; margin-top: 3px; }.report-filter-box svg { position: absolute; z-index: 1; left: 10px; top: 50%; width: 16px; transform: translateY(-50%); color: var(--muted); pointer-events: none; }.report-filters select { height: 34px; min-height: 34px; padding: 4px 9px 4px 32px; font-size: .68rem; }
        .report-types { padding: 10px 14px; }.report-types h2 { margin-bottom: 8px; font-size: .9rem; }.report-type-grid { display: grid; grid-template-columns: repeat(3,minmax(0,1fr)); gap: 10px; }.report-type { position: relative; min-width: 0; height: 67px; display: grid; grid-template-columns: 48px 1fr; gap: 12px; align-items: center; padding: 8px 12px; border: 1px solid var(--line); border-radius: 8px; background: white; color: var(--ink); text-align: left; cursor: pointer; }.report-type.active { border-color: var(--green); background: linear-gradient(90deg,#edf9f2,#f8fdfb); }.report-type-icon { width: 44px; height: 44px; display: grid; place-items: center; border-radius: 8px; color: var(--green-dark); background: var(--mint); }.report-type-icon.blue { color: var(--blue); background: var(--blue-soft); }.report-type h3 { font-size: .76rem; }.report-type p { margin-top: 4px; color: var(--muted); font-size: .63rem; line-height: 1.2; }.report-type .check { display: none; position: absolute; top: 7px; right: 8px; color: var(--green); }.report-type.active .check { display: block; }
        .report-preview { min-height: 0; display: grid; grid-template-rows: 50px minmax(0,1fr); padding: 10px 14px; overflow: hidden; }.preview-header { display: flex; align-items: flex-start; justify-content: space-between; gap: 14px; }.preview-header h2 { font-size: .95rem; }.preview-header p { margin-top: 3px; font-size: .66rem; color: var(--muted); }.export-actions { display: flex; gap: 8px; }.export-actions .btn { min-height: 34px; font-size: .68rem; }.export-actions .excel { background: var(--green); border-color: var(--green); color: white; }
        .preview-grid { min-height: 0; display: grid; grid-template-columns: minmax(0,1.35fr) minmax(260px,.75fr) minmax(280px,.9fr); gap: 10px; }.preview-panel { min-height: 0; overflow: hidden; padding: 8px; border: 1px solid var(--line); border-radius: 7px; }.preview-panel h3 { font-size: .72rem; }.preview-chart { height: calc(100% - 20px); min-height: 0; }.preview-chart canvas { width: 100%!important; height: 100%!important; }
        .period-summary { display: grid; grid-template-rows: auto repeat(4,1fr); }.summary-line { display: grid; grid-template-columns: 20px 1fr auto; gap: 7px; align-items: center; border-bottom: 1px solid #edf2f8; font-size: .64rem; }.summary-line svg { width: 15px; color: var(--blue); }.summary-line strong { white-space: nowrap; }
        .distribution { display: grid; grid-template-rows: auto minmax(0,1fr); }.distribution-content { min-height: 0; display: grid; grid-template-columns: 48% 52%; align-items: center; }.distribution-legend { display: grid; gap: 6px; font-size: .62rem; color: var(--muted); }.distribution-legend span { white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }.distribution-dot { display: inline-block; width: 8px; height: 8px; margin-right: 5px; border-radius: 50%; }
        @media(max-width:1180px){body:has(.reports-screen){overflow:auto}.reports-screen{height:auto;grid-template-rows:auto}.report-kpis,.report-filters{grid-template-columns:repeat(2,minmax(0,1fr))}.report-type-grid,.preview-grid{grid-template-columns:1fr}.report-preview{min-height:900px}.preview-panel{min-height:250px}}
        @media(max-width:700px){.report-kpis,.report-filters,.report-type-grid{grid-template-columns:1fr}.reports-hero .hero-note{display:none}.preview-header{display:grid}}
    </style>

    <div class="reports-screen">
        <section class="reports-hero"><div><p class="eyebrow">RMGS - Registro y Monitoreo de Generacion Solar Guatemala</p><h1>Reportes</h1><p class="subtitle">Convierte los datos en decisiones para un Guatemala mas limpio y sostenible.</p></div><div class="hero-note"><i data-lucide="map-pin"></i><span>Guatemala, un pais con mas energia limpia</span></div></section>
        <section class="grid report-kpis">
            <article class="card report-kpi"><span class="report-kpi-icon"><i data-lucide="bar-chart-3"></i></span><div><p class="report-kpi-label">Generacion total</p><p class="report-kpi-value">{{ number_format($stats['actual_kwh']) }} kWh</p><p class="report-kpi-trend">+8% <span>vs. mes anterior</span></p></div></article>
            <article class="card report-kpi"><span class="report-kpi-icon"><i data-lucide="leaf"></i></span><div><p class="report-kpi-label">CO2 evitado</p><p class="report-kpi-value">{{ number_format($stats['co2_tons'],1) }} t</p><p class="report-kpi-trend">+14% <span>vs. mes anterior</span></p></div></article>
            <article class="card report-kpi"><span class="report-kpi-icon"><i data-lucide="house"></i></span><div><p class="report-kpi-label">Granjas activas</p><p class="report-kpi-value">{{ number_format($stats['active_farms']) }}</p><p class="report-kpi-trend">+20% <span>vs. mes anterior</span></p></div></article>
            <article class="card report-kpi"><span class="report-kpi-icon blue"><i data-lucide="grid-2x2"></i></span><div><p class="report-kpi-label">Paneles instalados</p><p class="report-kpi-value">{{ number_format($stats['panels']) }}</p><p class="report-kpi-trend">+12% <span>vs. mes anterior</span></p></div></article>
        </section>
        <section class="card report-filters">
            <label>Periodo<span class="report-filter-box"><i data-lucide="calendar-days"></i><select><option>{{ $latestPeriod?->translatedFormat('F Y') ?? 'Todos' }}</option></select></span></label>
            <label>Departamento<span class="report-filter-box"><i data-lucide="map-pin"></i><select><option>Todos los departamentos</option>@foreach($departments as $department)<option>{{ $department->name }}</option>@endforeach</select></span></label>
            <label>Granja<span class="report-filter-box"><i data-lucide="landmark"></i><select><option>Todas las granjas</option>@foreach($farms as $farm)<option>{{ $farm->name }}</option>@endforeach</select></span></label>
            <label>Tipo de reporte<span class="report-filter-box"><i data-lucide="file-text"></i><select id="report-type-select"><option value="generation">Generacion de energia</option><option value="environment">Impacto ambiental</option><option value="executive">Resumen ejecutivo</option></select></span></label>
        </section>
        <section class="card report-types"><h2>Selecciona un tipo de reporte</h2><div class="report-type-grid"><button class="report-type active" data-report-type="generation"><span class="report-type-icon"><i data-lucide="bar-chart-3"></i></span><span><h3>Generacion de energia</h3><p>Energia generada, comparativas y tendencias.</p></span><i class="check" data-lucide="circle-check"></i></button><button class="report-type" data-report-type="environment"><span class="report-type-icon"><i data-lucide="leaf"></i></span><span><h3>Impacto ambiental</h3><p>CO2 evitado, equivalencias y beneficios.</p></span><i class="check" data-lucide="circle-check"></i></button><button class="report-type" data-report-type="executive"><span class="report-type-icon blue"><i data-lucide="pie-chart"></i></span><span><h3>Resumen ejecutivo</h3><p>Vista general del desempeno del sistema.</p></span><i class="check" data-lucide="circle-check"></i></button></div></section>
        <section class="card report-preview" id="report-preview"><header class="preview-header"><div><h2>Vista previa del reporte</h2><p><strong id="preview-type-name">Generacion de energia</strong> - {{ $latestPeriod?->translatedFormat('F Y') ?? 'Todos los periodos' }}<br>Todos los departamentos - Todas las granjas</p></div><div class="export-actions"><a class="btn" href="{{ route('reports.print') }}" target="_blank"><i data-lucide="file-down"></i>Exportar PDF</a><a class="btn excel" href="{{ route('reports.csv') }}"><i data-lucide="sheet"></i>Exportar Excel</a></div></header><div class="preview-grid"><article class="preview-panel"><h3>Generacion de energia (kWh)</h3><div class="preview-chart"><canvas id="report-generation-chart"></canvas></div></article><article class="preview-panel period-summary"><h3>Resumen del periodo</h3><div class="summary-line"><i data-lucide="zap"></i><span>Generacion total</span><strong>{{ number_format($stats['actual_kwh']) }} kWh</strong></div><div class="summary-line"><i data-lucide="bar-chart-3"></i><span>Promedio diario</span><strong>{{ number_format($stats['daily_average']) }} kWh</strong></div><div class="summary-line"><i data-lucide="trending-up"></i><span>Maxima registrada</span><strong>{{ number_format($maxGeneration) }} kWh</strong></div><div class="summary-line"><i data-lucide="trending-down"></i><span>Minima registrada</span><strong>{{ number_format($minGeneration) }} kWh</strong></div></article><article class="preview-panel distribution"><h3>Distribucion por departamento</h3><div class="distribution-content"><div class="preview-chart"><canvas id="report-department-chart"></canvas></div><div class="distribution-legend" id="department-legend"></div></div></article></div></section>
    </div>
    <script>
        const reportSeries=@json($generationSeries),departmentSeries=@json($departmentSeries),reportLabels=Object.keys(reportSeries),departmentLabels=Object.keys(departmentSeries),colors=['#0aa574','#1689f4','#65b9f5','#9bd4fb','#8ca1bd'];
        new Chart(document.getElementById('report-generation-chart'),{type:'line',data:{labels:reportLabels,datasets:[{data:reportLabels.map(key=>reportSeries[key].actual),borderColor:'#0aa574',backgroundColor:'rgba(10,165,116,.11)',fill:true,tension:.35,pointRadius:0,borderWidth:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{color:'#e8eff7'},ticks:{font:{size:8}}},y:{grid:{color:'#e8eff7'},ticks:{font:{size:8}}}}}});
        new Chart(document.getElementById('report-department-chart'),{type:'doughnut',data:{labels:departmentLabels,datasets:[{data:Object.values(departmentSeries),backgroundColor:colors,borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'58%',plugins:{legend:{display:false}}}});
        const total=Object.values(departmentSeries).reduce((sum,value)=>sum+Number(value),0);document.getElementById('department-legend').innerHTML=departmentLabels.map((name,index)=>`<span><i class="distribution-dot" style="background:${colors[index%colors.length]}"></i>${name}: <strong>${total?Math.round(departmentSeries[name]/total*100):0}%</strong></span>`).join('');
        const reportNames={generation:'Generacion de energia',environment:'Impacto ambiental',executive:'Resumen ejecutivo'},reportSelect=document.getElementById('report-type-select'),reportButtons=[...document.querySelectorAll('[data-report-type]')];function selectReport(type){reportButtons.forEach(button=>button.classList.toggle('active',button.dataset.reportType===type));reportSelect.value=type;document.getElementById('preview-type-name').textContent=reportNames[type]}reportButtons.forEach(button=>button.addEventListener('click',()=>selectReport(button.dataset.reportType)));reportSelect.addEventListener('input',()=>selectReport(reportSelect.value));
    </script>
@endsection
